### ISSUE TITLE
Compatible with 0.9.4 version?

### ISSUE THREAD

**Issue by Nisthar** [qgp9/nodebb-plugin-magicblock#2]
Hi, This is a nice plugin. Does it run under my 0.9.4 version?

**Comment by qgp9** [comment]
Hi @Nisthar actually, I have never tested/developed this plugin with other than v.1.0.0, so frankly have no idea. Let me try to figure it out.

**Comment by Nisthar** [comment]
@qgp9 Okay

**Comment by qgp9** [comment]
Hey @Nisthar 
I just published v0.1.6 to npm. It seems that it works well.
Testing server for NodeBB@0.9.4 and MagicBlock@0.1.6 is on Cloud9 now.
https://nodebb-0-9-4-magicblock-qgp9.c9users.io/topic/2/nodebb-plugin-magicblock-test
You can test it by yourserf, no login required in `General category`

But I'm not sure how long it will be on-service after I leave soon. maybe two hours? :)

**Comment by Nisthar** [comment]
@qgp9 Thanks :+1: I'll test it.

Anyway, do i need to download it from acp or git clone and place it at node_modules? Last time i checked, I can't see the plugin listed in the downloadable plugins.

**Comment by qgp9** [comment]
I think it's because I put a only v1.x.x compatibility in configuration. I may improve this soon.
In the mean time, the best way to install the plugin will be
`npm install nodebb-plugin-magicblock`.
Also you better to remember how to disable a plugin on command line when you use a very young module which isn't tested enough and can crash admin UI. :P

**Comment by Nisthar** [comment]
@qgp9 BTW is it compatible along with Markdown plugin?

**Comment by qgp9** [comment]
@Nisthar YES, MagicBlock just work after Markdown plugin. 
This means that MagicBlock knows nothing of markdown syntax but just handle HTML string which is generated by Markdown plugin.
So If you do `{{#red http://a.com}}`, in real, MagicBlock will see 
`{{#red <a href="http://a.com">http://a.com</a>}}`

**Comment by Nisthar** [comment]
@qgp9 Ok
